config/routes.rb
Hm3::Application.routes.draw do
  resources :appointments

  resources :services

  resources :professional_services



  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :professionals


  authenticated :user do
    root :to => 'professionals#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :messages, only: [:index, :create]

  match 'blog' => 'blog#index'
  match 'blog/:title' => 'blog#post'
  

end

app/models/professional.rb
class Professional < ActiveRecord::Base
  attr_accessible :address, :clinic, :experience, :final_price, :gmaps, :information, :latitude, :longitude, :market_price, :name, :picture, :saving_price, :education, :profession, :speciality, :service_ids

  mount_uploader :picture, PictureUploader

  acts_as_gmappable

  monetize :final_price

  validates :address, :clinic, :experience, :gmaps, :information, :latitude, :longitude, :name, :picture, :education, :presence => true 

  has_many  :professional_services
  has_many  :services, :through => :professional_services



 
  def gmaps4rails_address
#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
  address
 end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController

  
  # GET /professionals
  # GET /professionals.json
  def index

    #ransack implementation
    @q = Professional.search(params[:q])
    @professionals = @q.result(distinct: true)

    #gmaps4rails implementation
    @json = Professional.all.to_gmaps4rails
    @json = Professional.all.to_gmaps4rails  do |professional, marker|
    marker.infowindow render_to_string(:partial => "/professionals/gmaps4rails_infowindow", :locals => { :professional => professional})
    marker.picture({
                  :picture => "/img/Clinica Tabancura.png",
                  :width   => 30,
                  :height  => 30,
                 })
   end 

   

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @professionals }
    end
  end

  # GET /professionals/1
  # GET /professionals/1.json
  def show
    @professional = Professional.find(params[:id])
    @json = Professional.find(params[:id]).to_gmaps4rails
    @json = Professional.find(params[:id]).to_gmaps4rails  do |professional, marker|
    marker.infowindow render_to_string(:partial => "/professionals/gmaps4rails_info_profile", :locals => { :professional => professional})
    marker.picture({
                  :picture => "/img/Clinica Tabancura.png",
                  :width   => 30,
                  :height  => 30,
                 })
   end 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @professional }
    end
  end

  # GET /professionals/new
  # GET /professionals/new.json
  def new
    @professional = Professional.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @professional }
    end
  end

  # GET /professionals/1/edit
  def edit
    @professional = Professional.find(params[:id])
  end
    
  # POST /professionals
  # POST /professionals.json
  def create
    @professional = Professional.new(params[:professional])
     
    respond_to do |format|
      if @professional.save
        format.html { redirect_to @professional, notice: 'Professional was successfully created.' }
        format.json { render json: @professional, status: :created, location: @professional }
      else
        format.html { render action: "new" }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /professionals/1
  # PUT /professionals/1.json
  def update
    @professional = Professional.find(params[:id])
    params[:professional][:service_ids] ||= []

      
    
    respond_to do |format|
      if @professional.update_attributes(params[:professional])
        format.html { redirect_to @professional, notice: 'Professional was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professionals/1
  # DELETE /professionals/1.json
  def destroy
    @professional = Professional.find(params[:id])
    @professional.destroy

    respond_to do |format|
      format.html { redirect_to professionals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<div class="container">
  <div class="row">
    <div class="span6 offset3">
       <div class="well well large">
         <%= simple_form_for(@professional) do |f| %>
         <%= f.error_notification %>

           <div class="form-inputs">
             <%= f.input :name, :label => "Nombre" %>
             <%= f.input :profession, :label => "Profesión" %>
             <%= f.input :speciality, :label => "Especialidad" %>
             <%= f.input :address, :label => "Dirección" %>
             <%= f.input :clinic, :label => "Clinica" %>
             <%= f.input :education, :label => "Educacion" %>
             <%= f.input :information, :label => "Información" %>
             <%= f.input :picture, :label => "Foto" %>
             <%= f.input :experience, :label => "Experiencia" %>
             <%= f.input :market_price %>
             <%= f.input :saving_price %>
             <%= f.input :final_price %>
             <%= f.input :longitude %>
             <%= f.input :latitude %>
             <%= f.input :gmaps %>

            </div class="field">
             <% Service.all.each do |service| %>
             <%= check_box_tag "professional[service_ids][]", service.id, @professional.services.include?(service) %>
             <%= label_tag dom_id(service), service.name %><br>
             <% end %>
           </div>

          <div class="form-actions">
           <%= f.button :submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  

app/views/professionals/_gmaps4rails_infowindow.html.erb
<div class="span2">
  <%= link_to (image_tag professional.picture_url(:thumb)), professional %>
</div>

<div class="span4">
  <h3><%= link_to professional.name, professional, :class => "newcolor" %></h3>

  <h4><%= professional.profession %></h4>

  <p><%= professional.clinic %></p>

  <p><%= professional.address %></p>
</div>

app/views/professionals/edit.html.erb
<h1>Edición de los profesionales</h1>

<%= render 'form' %>

<%= link_to 'Back', professionals_path, class: "btn btn btn-default" %>

<%= link_to 'Show', @professional, class: "btn btn btn-default" %> 

app/views/professionals/index.html.erb
<%= gmaps4rails(@json) %>

<section id="search" class="search">
  <div class="row-fluid">
    <div class="span4 offset4">
     
      
      <div class="input-append">

      <%= search_form_for @q do |f| %>

      <%= f.collection_select :services_id_eq, Service.order(:name), :id, :name, :prompt => 'Elige un servicio' %>
       <%= f.submit "Buscar", class: "btn btn btn-inverse"  %>
      <% end %>
      </div>
 
    </div>
  </div>
</section>


<section id='professional' >
    <% @professionals.each do |professional| %>
    <div class="container">
     <div class="well well large">
      <article class='row-fluid'>
          <div class="pro_thumb span4 offset2">
            <%= link_to (image_tag professional.picture_url(:thumb)), professional %>
          </div>
          <div class="info_pro span5">
            
            <h3> <%= link_to professional.name, professional, :class => "newcolor" %></h3>
            <ul>
                <h4><%= professional.profession %> </h4>
                <h5> <%= professional.clinic %></h5>
                <h5> <%= professional.address %></h5>
                              
                <% if can? :update, @professional %>
                <%= link_to 'Edit', edit_professional_path(professional), class: "btn btn-default" %>
                <% end %>

                <% if can? :destroy, @professional %>
                <%= link_to 'Destroy', professional, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
                <% end %>
          </div>
         </div> 

      </article>

     </div>
    <%end%>
    
    
    <% if can? :update, @professional %>
    <%= link_to 'New Professional', new_professional_path, class: "btn btn-info" %>
    <%end%>
</section>
        
</div>
  
    
    
  

app/views/professionals/new.html.erb
<h1>New professional</h1>

<%= render 'form' %>

<%= link_to 'Back', professionals_path, class: "btn btn-default" %>

app/views/professionals/show.html.erb
      <div class="container"> 
        <div class="row-fluid">
            <div class="picture span2 offset1 ">
              <%= image_tag(@professional.picture_url, :width => 200) if @professional.picture.present? %>
            </div>
            <div class="main_info span4">
              <h3> <%= @professional.name %></h3>
              <h4> <%= @professional.profession %></h3>            
              <h5> <%= @professional.speciality %></h5>
              <p> <%= @professional.experience %> años de experiencia
              </p>
              <%= social_share_button_tag(@professional.name) %>
              <%= link_to 'Agendar', edit_professional_path(@professional), class: "btn btn btn-default" %> 

            </div>
            <div class="social_buttons span4 ">              
              <%= gmaps({
          "map_options" => {:container_class => "map_container_renamed","auto_zoom" => false, "zoom" => 15 },
           "markers" => {"data" => @json }
           })
          %>         
            </div> 
          </div>           
            <div class="row-fluid">  
                <div class="biography span6 offset1 "> 
                  <div class="well well large">
                    <h4>Biografia</h4></br>
                    <p><%= @professional.information %></p>
                 </div>
               </div>
                <div class="info_details span4 "> 
                  <div class="well well large">
                    <h4>Detalles</h4></br>
                    <table class="table table-hover ">  
                        <tbody>
                        <tr>
                          <td><i class="icon-book icon-2x"></i></td>
                          <td><%= @professional.education %></td>
                        </tr> 
                        <tr>
                          <td><i class="icon-hospital icon-2x"></i></td>
                          <td><%= @professional.clinic %></p></td>
                        </tr>
                        <tr>  
                          <td><i class="icon-map-marker icon-2x"></i></td>
                          <td><%= @professional.address %></p></td>
                        </tr>
                       </tbody>              
                    </table>
                  </div>     
                </div>
            </div>
            <div class="row-fluid">  
              <div class="services_pro span4 offset1 "> 
                  <div class="well well large">
                    <h4>Servicios</h4></br>
                    <p><% @professional.services.each do |service| %></p>
                        <p><%= service.name %></p>
                        <% end %>                      
                  </div>
              </div>
        </div>

          <% if can? :update, @professional %>
          <%= link_to 'Edit', edit_professional_path(@professional), class: "btn btn btn-default" %> 
          <% end %>
        </div>